apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dpop-client-cert-renew
  namespace: default
spec:
  secretName: dpop-client-tls-secret
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: my-valid-client
  usages:
    - client auth
